### ISSUE TITLE
No summary on error

### ISSUE THREAD

**Issue by HugoHeneault** [stnvh/gulp-tinypng-compress#10]
Hi again, 

After I reached my monthly limit, your plugin stops, but... There's no summary. 
Why ? :cry:

**Comment by stnvh** [comment]
`log: true` in config (to view errors)!

**Comment by HugoHeneault** [comment]
I was talking about `summarize: true` summary. ;-)

**Comment by stnvh** [comment]
Is the desired behavior to output an error within the summary if one occurs?

**Comment by HugoHeneault** [comment]
Well, when 250+ files are minified, then I got an API limit error for the
last one and I have no summary of how my files have been compressed, that
make me sad. :'(
