### ISSUE TITLE
tinypng-compress for webpack

### ISSUE THREAD

**Issue by stephanedemotte** [stnvh/gulp-tinypng-compress#12]
Hi !

We LOVE your plugin for gulp.
We're thinking about switching for Webpack. But we will miss your plugin.

It would be very great to have your plugin on Webpack :)

Thanks for all !

**Comment by stnvh** [comment]
I'll certainly look into a webpack version when I can - thanks for the appreciation! :+1:

**Comment by ca-miked** [comment]
+100
