### ISSUE TITLE
Create .sig File when option is used

### ISSUE THREAD

**Issue by dnnsthnnr** [stnvh/gulp-tinypng-compress#14]
In my usage the plugin didn't create a .sig file and so always uploaded and compressed all the images in the folder. I could fix the problem by creating the .sig file manually.

would be great if the .sig file would be created automatically when the option is used.

**Comment by stnvh** [comment]
Wow, I'm surprised this got overlooked! I'll get fixing this asap and add tests for it. Cheers for raising this.

**Comment by stnvh** [comment]
I looked into it, the file does appear to be created. The only thing I can think is you've set the `sigFile` option to `true`, where it needs to be a filename like so: `sigFile: '.sig'`
