### ISSUE TITLE
sigFile not created

### ISSUE THREAD

**Issue by ogrosko** [stnvh/gulp-tinypng-compress#16]
Hi
I have following gulp task

`gulp.task('tinypng', function () {
    gulp.src([
            './uploads/**/*.{png,jpg,jpeg}'
        ])
        .pipe(tinypng({
            key: 'MY_TINY_PNG_KEY',
            sameDest: true,
            sigFile: './.sigFile',
            log: true
        }));
});`

but no `.sigFile` is created after image compression

**Comment by stnvh** [comment]
This needs further investigation, on my setup and in tests it seems to create the sigfile fine, it may be a node version incompatibility, or something to do with sameDest.. i'll look into it, thanks

**Comment by stnvh** [comment]
Fixed in [1.2.3](https://github.com/stnvh/gulp-tinypng-compress/releases/tag/1.2.3)
