### ISSUE TITLE
Dependency warning

### ISSUE THREAD

**Issue by ethanclevenger91** [stnvh/gulp-tinypng-compress#17]
`minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

**Comment by stnvh** [comment]
I need to review dependencies, kind folks (@nymo) have made PRs to fix this so I'll get on this soon, thanks

**Comment by stnvh** [comment]
Fixed in [1.2.2](https://github.com/stnvh/gulp-tinypng-compress/releases/tag/1.2.2)
