### ISSUE TITLE
No images returned

### ISSUE THREAD

**Issue by arkwis** [stnvh/gulp-tinypng-compress#2]
I have installed the plugin according to instructions, but I'm not getting any actual images in the results, just copied folder structure.

```
var tinypngcomp = require('gulp-tinypng-compress');

gulp.task('tinypngcomp', function () {
    gulp.src('public/images/**/*.{png,jpg,jpeg}')
        .pipe(tinypngcomp({
            key: 'API_KEY',
            checkSigs: true,
            sigFile: 'public/images/.tinypng-sigs'
        }))
        .pipe(gulp.dest('public/tiny'));
});
```

The console only logs

```
[13:23:20] Starting 'tinypngcomp'...
[13:23:20] Finished 'tinypngcomp' after 5.06 ms
```

Not sure if related, but the original gulp-tinypng works fine with the same source and API_KEY.

**Comment by stnvh** [comment]
What's the output if you add an error handle e.g:

``` js
var gulp = require('gulp'),
    tinypngcomp = require('gulp-tinypng-compress');

gulp.task('tinypngcomp', function () {
    gulp.src('public/images/**/*.{png,jpg,jpeg}')
        .pipe(tinypngcomp({
            key: 'API_KEY',
            checkSigs: true,
            sigFile: 'public/images/.tinypng-sigs'
        }).on('error', function(err) {
            console.log(err.message);
        }))
        .pipe(gulp.dest('public/tiny'));
});
```

Without a key, the following shows in the console:
`Upload response JSON parse failed, invalid data returned from API. Failed with message: Cannot read property 'url' of undefined`

The only way I could make your example fail was if I didn't include an API key. The previous version may of ran without one, but it wouldn't of been compressing the images, just copying them.

**Comment by arkwis** [comment]
Ah, I should've included error logs from the beginning. All the files fail with this:

```
Upload failed for **.png with error: CERT_UNTRUSTED
```

which I now realize is not an issue with the code.

**Comment by stnvh** [comment]
Try running, in Terminal: `npm config set strict-ssl false` then run gulp again

**Comment by stnvh** [comment]
It seems to be a node version based issue, according to [this](http://stackoverflow.com/questions/21855035/ssl-error-cert-untrusted-while-using-npm-command). I'm sure it can be set programatically. I'll look into a permanent fix soon.
