### ISSUE TITLE
NPM audit finds vulnerabilities

### ISSUE THREAD

**Issue by thomasjsn** [stnvh/gulp-tinypng-compress#25]
* `gulp-tinypng-compress > request > hawk > boom > hoek`
* `gulp-tinypng-compress > request > hawk > cryptiles > boom > hoek`
* `gulp-tinypng-compress > request > hawk > hoek`
* `gulp-tinypng-compress > request > hawk > sntp > hoek`
* `gulp-tinypng-compress > minimatch`
* `gulp-tinypng-compress > request > tunnel-agent`
* `gulp-tinypng-compress > request`
* `gulp-tinypng-compress > request > hawk`

Any reason why `request` and `minimatch` cant be upgraded to the latest version?

**Comment by thomasjsn** [comment]
If you cant think of any then I'll update them, do some testing av submit a PR :)

**Comment by stnvh** [comment]
Fixed in [1.2.2](https://github.com/stnvh/gulp-tinypng-compress/releases/tag/1.2.2)
