### ISSUE TITLE
checkSigs dont work

### ISSUE THREAD

**Issue by stephanedemotte** [stnvh/gulp-tinypng-compress#4]
Hi !

your plugin look very promising !!!

But when i try to play with it, the checkSigs don't work.
No file has been create, and in each new gulp, the plugin compress all my assets...

It's a work in progress ?
Or i have something wrong ?

thanks !

**Comment by stnvh** [comment]
Could you post the contents of your Gulpfile?

**Comment by stephanedemotte** [comment]
forget it, everything works great :dancer: 

Thanks a lot for your work !

**Comment by stnvh** [comment]
No worries :+1:
