### ISSUE TITLE
Support for same source/destination?

### ISSUE THREAD

**Issue by ericcholis** [stnvh/gulp-tinypng-compress#5]
The cache functionality currently doesn't work if the source and destination are the same. The hash is calculated on the file on-disk not on the result from TinyPNG. This makes sense when the source and destination are different. However, it causes cache misses when source and destination are the same.

Digging through the source now to see where I might be able to implement an optional update based on the resulting file. However, my experience with gulp plugins is pretty limited.

**Comment by stnvh** [comment]
I never considered this, well spotted. I shouldn't think it would be too hard to add logic for same-directory cases. I'll get working on something for the next release

**Comment by stnvh** [comment]
This would only work if explicitly stated e.g in the configuration as `sameDest: true` or something similar, as gulp plugins have no idea where the files they handle get written to  - their job is to simply transform the file, then pass it/them on to the next plugin.

**Comment by ericcholis** [comment]
Agreed, that's what I had in mind. It would also likely fail if piped to something else that modified the file.

**Comment by stnvh** [comment]
Pushed into [dev/next](https://github.com/stnvh/gulp-tinypng-compress/commit/f373ed53e18911ef0db5dafccef8426b6942ae48), will stage for release soon, I just need to iron out a few other things

**Comment by ericcholis** [comment]
Outstanding @stnvh, that was fast!

**Comment by stnvh** [comment]
Added in [1.1.6](https://github.com/stnvh/gulp-tinypng-compress/releases/tag/1.1.6)

**Comment by ericcholis** [comment]
Thanks again, this is working quite well. It saved me 491 API requests for every gulp task run.
