### ISSUE TITLE
Use file path for check signature

### ISSUE THREAD

**Issue by stefanozoffoli** [stnvh/gulp-tinypng-compress#6]
Hi,
thank you for this plugin, it's really useful.
When I use sameDest option, image signatures are calculated using only file names.

So when I have two image with the same name (but in different path), the second image's signature overwrites the first image's signature, and the next time both images are processed again and so on.

Is it possible to use file path to identify signatures?

**Comment by stnvh** [comment]
Marking as bug. Will fix for next release :)

**Comment by stefanozoffoli** [comment]
Thank you! :smile:

**Comment by stnvh** [comment]
Closed in 1.1.7 :+1: (adb76eb5)
