### ISSUE TITLE
sigFile does not handle deleted files

### ISSUE THREAD

**Issue by HugoHeneault** [stnvh/gulp-tinypng-compress#8]
Hi there, 

Thanks for your great tool and the improvements you're doing. :smiley: 

I have an issue with `sigFile` option: when you delete the dist folder, files are not reprocessed. 
So if we are a team building our dist folder, my team won't process the files which are in it. 

I'm not sure if I'm clear: I can provide more informations if you need. 

Thanks again, and have a nice day!

**Comment by stnvh** [comment]
I don't think this would be an option. A gulp plugin is essentially a 'filter'; an array of files goes in, and modified ones come out. There is no knowing the target directory at the point of file processing, as files are written with `gulp.dest()` at the end of the stream, so testing for the target directory existence isn't possible.
In theory something like this could be added, but it would involve passing the target dir as a config option (ugly).

You could however change your gulpfile to include a watch task on the dist folder, upon removal, run the plugin without signature checks, or remove the sigfile entirely then re-process.

Hope this helps!

**Comment by HugoHeneault** [comment]
Thanks, I'll do it. I'm surprised it's not possible in the gulp process, but no problem. :)
