### ISSUE TITLE
upload concurrency

### ISSUE THREAD

**Issue by HugoHeneault** [stnvh/gulp-tinypng-compress#9]
Hi there, 

It could be great to allow multiple upload at the same time (like 4 by 4 uploads), because tinypng serv is a little slow while compressing. 
grunt-tinypng is faster, because it allows connection concurrency. ;)

Thanks!

**Comment by stnvh** [comment]
Definitely a feature worth including! Will work this into next release :+1:

**Comment by HugoHeneault** [comment]
Awesome! Thanks a lot! :D

2015-10-26 13:21 GMT+01:00 Stan Hutcheon notifications@github.com:

**Comment by stnvh** [comment]
I've added an untested concurrent version on the [`dev/next`](https://github.com/stnvh/gulp-tinypng-compress/commit/a3b3ee447b7d570f1375177ebd18e59f803d5e31) branch. If you want to test, add 
`"gulp-tinypng-compress": "stnvh/gulp-tinypng-compress#a3b3ee44"` 
to your package.json, then run `npm update`. Let me know if it works!

**Comment by HugoHeneault** [comment]
Tested. Seems to work perfectly! Awesome!
How many connection is it running?

**Comment by HugoHeneault** [comment]
I have a 100mb connection, and the processing time of 300+ files (30mo) is now 2mn when it was 21mn before. Really awesome!

Thanks a lot for your faster-than-light update. :smiley:

**Comment by stnvh** [comment]
I don't think there is a concurrency limit imposed - it just uploads all of the images at once! I'm not sure of the performance implications, and it would make it very easy to bust your request limit if you have a lot of pics, so a limit (with conf option to override) may be needed!

**Comment by HugoHeneault** [comment]
Yes I think so too. grunt-tinypng upload 5by5 images. 
With a bad connection, nothing will upload (and tinypng may block or not respond for 300 requests)

**Comment by stnvh** [comment]
This is pretty much done on the `dev/next` branch. Credit given for the feature suggestion ;)

**Comment by HugoHeneault** [comment]
Thanks a lot! :)
